countries = [
    {name: 'Gambia Dalasi', value:'GMD'},
    {name: 'Senegal Franc', value:'CFA'},
    {name: 'Nigerian Naira', value:'N'},
  ];

//  // countries = [{value: "GMD", name: "Dalasi"},
//                {value:"AFA":"Afghani"},{value:"AFN":"Afghani"},{value:"ALK":"Albanian old lek"},
//                {value:"ALL":"Lek"},{value:"DZD":"Algerian Dinar"},{value:"USD":"US Dollar"},
//                {value:"ADF":"Andorran Franc"},{value:"ADP":"Andorran Peseta"},{value:"EUR":"Euro"},
//                {value:"AOR":"Angolan Kwanza Readjustado"},{value:"AON":"Angolan New Kwanza"},{value:"AOA":"Kwanza"},
//                {value:"XCD":"East Caribbean Dollar"},{value:"ARA":"Argentine austral"},{value:"ARS":"Argentine Peso"},
//                {"value:ARL":"Argentine peso ley"},{value:"ARM":"Argentine peso moneda nacional"},{value:"ARP":"Peso argentino"},
//                {value:"AMD":"Armenian Dram"},{value:"AWG":"Aruban Guilder"},{value:"AUD":"Australian Dollar"},
//                {value:"ATS":"Austrian Schilling"},{value:"AZM":"Azerbaijani manat"},{value:"AZN":"Azerbaijanian Manat"},
//                {value:"BSD":"Bahamian Dollar"},{value:"BHD":"Bahraini Dinar"},{value:"BDT":"Taka"},{value:"BBD":"Barbados Dollar"},
//                {value:"BYR":"Belarussian Ruble"},{value:"BEC":"Belgian Franc (convertible)"},{value:"BEF":"Belgian Franc (currency union with LUF)"},
//                {value:"BEL":"Belgian Franc (financial)"},{value:"BZD":"Belize Dollar"},{value:"XOF":"CFA Franc BCEAO"},
//                {value:"BMD":"Bermudian Dollar"},{value:"INR":"Indian Rupee"},{value:"BTN":"Ngultrum"},{value:"BOP":"Bolivian peso"},
//                {value:"BOB":"Boliviano"},{value:"BOV":"Mvdol"},{value:"BAM":"Convertible Marks"},{value:"BWP":"Pula"},{value:"NOK":"Norwegian Krone"},
//                {value:"BRC":"Brazilian cruzado"},{value:"BRB":"Brazilian cruzeiro"},{value:"BRL":"Brazilian Real"},{value:"BND":"Brunei Dollar"},
//                {value:"BGN":"Bulgarian Lev"},{value:"BGJ":"Bulgarian lev A/52"},{value:"BGK":"Bulgarian lev A/62"},{value:"BGL":"Bulgarian lev A/99"},
//                {value:"BIF":"Burundi Franc"},{value:"KHR":"Riel"},{value:"XAF":"CFA Franc BEAC"},{value:"CAD":"Canadian Dollar"},{value:"CVE":"Cape Verde Escudo"},
//                {value:"KYD":"Cayman Islands Dollar"},{value:"CLP":"Chilean Peso"},{value:"CLF":"Unidades de fomento"},{value:"CNX":"Chinese People's Bank dollar"},
//                {value:"CNY":"Yuan Renminbi"},{value:"COP":"Colombian Peso"},{value:"COU":"Unidad de Valor real"},{value:"KMF":"Comoro Franc"},
//                {value:"CDF":"Franc Congolais"},{value:"NZD":"New Zealand Dollar"},{"CRC":"Costa Rican Colon"},{"HRK":"Croatian Kuna"},
//                {value:"CUP":"Cuban Peso"},{value:"CYP":"Cyprus Pound"},{value:"CZK":"Czech Koruna"},{value:"CSK":"Czechoslovak koruna"},
//                {value:"CSJ":"Czechoslovak koruna A/53"},{value:"DKK":"Danish Krone"},{value:"DJF":"Djibouti Franc"},
//                {value:"DOP":"Dominican Peso"},{value:"ECS":"Ecuador sucre"},{value:"EGP":"Egyptian Pound"},{value:"SVC":"Salvadoran colón"},
//                {value:"EQE":"Equatorial Guinean ekwele"},{value:"ERN":"Nakfa"},{value:"EEK":"Kroon"},{value:"ETB":"Ethiopian Birr"},{value:"FKP":"Falkland Island Pound"},
//                {value:"FJD":"Fiji Dollar"},{value:"FIM":"Finnish Markka"},{value:"FRF":"French Franc"},{value:"XFO":"Gold-Franc"},{value:"XPF":"CFP Franc"},
//                {value:"DEM":"Deutsche Mark"},{value:"GHS":"Ghana Cedi"},{value:"GHC":"Ghanaian cedi"},{value:"GIP":"Gibraltar Pound"},
//                {value:"GMD":"Dalasi"},{value:"GEL":"Lari"},{value:"DDM":"East German Mark of the GDR (East Germany)"},
//                {value:"GRD":"Greek Drachma"},{"GTQ":"Quetzal"},{"GNF":"Guinea Franc"},{"GNE":"Guinean syli"},
//                {"GWP":"Guinea-Bissau Peso"},{"GYD":"Guyana Dollar"},{"HTG":"Gourde"},{"HNL":"Lempira"},
//                {"HKD":"Hong Kong Dollar"},{"HUF":"Forint"},{"ISK":"Iceland Krona"},{"ISJ":"Icelandic old krona"},
//                {"IDR":"Rupiah"},{"IRR":"Iranian Rial"},{"IQD":"Iraqi Dinar"},{"IEP":"Irish Pound (Punt in Irish language)"},
//                {"ILP":"Israeli lira"},{"ILR":"Israeli old sheqel"},{"ILS":"New Israeli Sheqel"},{"ITL":"Italian Lira"},
//                {"JMD":"Jamaican Dollar"},{"JPY":"Yen"},{"JOD":"Jordanian Dinar"},{"KZT":"Tenge"},{"KES":"Kenyan Shilling"},
//                {"KPW":"North Korean Won"},{"KRW":"Won"},{"KWD":"Kuwaiti Dinar"},{"KGS":"Som"},{"LAK":"Kip"},
//                {"LAJ":"Lao kip"},{"LVL":"Latvian Lats"},{"LBP":"Lebanese Pound"},{"LSL":"Loti"},
//                {"ZAR":"Rand"},{"LRD":"Liberian Dollar"},{"LYD":"Libyan Dinar"},{"CHF":"Swiss Franc"},
//                {"LTL":"Lithuanian Litas"},{"LUF":"Luxembourg Franc (currency union with BEF)"},{"MOP":"Pataca"},
//                {"MKD":"Denar"},{"MKN":"Former Yugoslav Republic of Macedonia denar A/93"},{"MGA":"Malagasy Ariary"},
//                {"MGF":"Malagasy franc"},{"MWK":"Kwacha"},{"MYR":"Malaysian Ringgit"},{"MVQ":"Maldive rupee"},
//                {"MVR":"Rufiyaa"},{"MAF":"Mali franc"},{"MTL":"Maltese Lira"},{"MRO":"Ouguiya"},
//                {"MUR":"Mauritius Rupee"},{"MXN":"Mexican Peso"},{"MXP":"Mexican peso"},{"MXV":"Mexican Unidad de Inversion (UDI)"},
//                {"MDL":"Moldovan Leu"},{"MCF":"Monegasque franc (currency union with FRF)"},{"MNT":"Tugrik"},{"MAD":"Moroccan Dirham"},
//                {"MZN":"Metical"},{"MZM":"Mozambican metical"},{"MMK":"Kyat"},{"NAD":"Namibia Dollar"},{"NPR":"Nepalese Rupee"},
//                {"NLG":"Netherlands Guilder"},{"ANG":"Netherlands Antillian Guilder"},{"NIO":"Cordoba Oro"},{"NGN":"Naira"},
//                {"OMR":"Rial Omani"},{"PKR":"Pakistan Rupee"},{"PAB":"Balboa"},{"PGK":"Kina"},{"PYG":"Guarani"},
//                {"YDD":"South Yemeni dinar"},{"PEN":"Nuevo Sol"},{"PEI":"Peruvian inti"},{"PEH":"Peruvian sol"},
//                {"PHP":"Philippine Peso"},{"PLZ":"Polish zloty A/94"},{"PLN":"Zloty"},{"PTE":"Portuguese Escudo"},
//                {"TPE":"Portuguese Timorese escudo"},{"QAR":"Qatari Rial"},{"RON":"New Leu"},{"ROL":"Romanian leu A/05"},
//                {"ROK":"Romanian leu A/52"},{"RUB":"Russian Ruble"},{"RWF":"Rwanda Franc"},{"SHP":"Saint Helena Pound"},
//                {"WST":"Tala"},{"STD":"Dobra"},{"SAR":"Saudi Riyal"},{"RSD":"Serbian Dinar"},{"CSD":"Serbian Dinar"},
//                {"SCR":"Seychelles Rupee"},{"SLL":"Leone"},{"SGD":"Singapore Dollar"},{"SKK":"Slovak Koruna"},{"SIT":"Slovenian Tolar"},
//                {"SBD":"Solomon Islands Dollar"},{"SOS":"Somali Shilling"},{"ZAL":"South African financial rand (Funds code) (discont"},
//                {"ESP":"Spanish Peseta"},{"ESA":"Spanish peseta (account A)"},{"ESB":"Spanish peseta (account B)"},
//                {"LKR":"Sri Lanka Rupee"},{"SDD":"Sudanese Dinar"},{"SDP":"Sudanese Pound"},{"SDG":"Sudanese Pound"},
//                {"SRD":"Surinam Dollar"},{"SRG":"Suriname guilder"},{"SZL":"Lilangeni"},{"SEK":"Swedish Krona"},
//                {"CHE":"WIR Euro"},{"CHW":"WIR Franc"},{"SYP":"Syrian Pound"},{"TWD":"New Taiwan Dollar"},{"TJS":"Somoni"},
//                {"TJR":"Tajikistan ruble"},{"TZS":"Tanzanian Shilling"},{"THB":"Baht"},{"TOP":"Pa'anga"},
//                {"TTD":"Trinidata and Tobago Dollar"},{"TND":"Tunisian Dinar"},{"TRY":"New Turkish Lira"},
//                {"TRL":"Turkish lira A/05"},{"TMM":"Manat"},{"RUR":"Russian rubleA/97"},{"SUR":"Soviet Union ruble"},
//                {"UGX":"Uganda Shilling"},{"UGS":"Ugandan shilling A/87"},{"UAH":"Hryvnia"},{"UAK":"Ukrainian karbovanets"},
//                {"AED":"UAE Dirham"},{"GBP":"Pound Sterling"},{"USN":"US Dollar (Next Day)"},{"USS":"US Dollar (Same Day)"},
//                {"UYU":"Peso Uruguayo"},{"UYN":"Uruguay old peso"},{"UYI":"Uruguay Peso en Unidades Indexadas"},
//                {"UZS":"Uzbekistan Sum"},{"VUV":"Vatu"},{"VEF":"Bolivar Fuerte"},{"VEB":"Venezuelan Bolivar"},
//                {"VND":"Dong"},{"VNC":"Vietnamese old dong"},{"YER":"Yemeni Rial"},{"YUD":"Yugoslav Dinar"},
//                {"YUM":"Yugoslav dinar (new)"},{"ZRN":"Zairean New Zaire"},{"ZRZ":"Zairean Zaire"},{"ZMK":"Kwacha"},
//                {"ZWD":"Zimbabwe Dollar"},{"ZWC":"Zimbabwe Rhodesian dollar"}];


