 countries = [{value: "GMD", name: "Dalasi"},
               {value:"AFA", name:"Afghani"},{value:"AFN", name:"Afghani"},{value:"ALK", name:"Albanian old lek"},
               {value:"ALL", name:"Lek"},{value:"DZD", name:"Algerian Dinar"},{value:"USD", name:"US Dollar"},
               {value:"ADF", name:"Andorran Franc"},{value:"ADP", name:"Andorran Peseta"},{value:"EUR", name:"Euro"},
               {value:"AOR", name:"Angolan Kwanza Readjustado"},{value:"AON", name:"Angolan New Kwanza"},{value:"AOA", name:"Kwanza"},
               {value:"XCD", name:"East Caribbean Dollar"},{value:"ARA", name:"Argentine austral"},{value:"ARS", name:"Argentine Peso"},
               {value:"ARL", name:"Argentine peso ley"},{value:"ARM", name:"Argentine peso moneda nacional"},{value:"ARP", name:"Peso argentino"},
               {value:"AMD", name:"Armenian Dram"},{value:"AWG", name:"Aruban Guilder"},{value:"AUD", name:"Australian Dollar"},
               {value:"ATS", name:"Austrian Schilling"},{value:"AZM", name:"Azerbaijani manat"},{value:"AZN", name:"Azerbaijanian Manat"},
               {value:"BSD", name:"Bahamian Dollar"},{value:"BHD", name:"Bahraini Dinar"},{value:"BDT", name:"Taka"},{value:"BBD", name:"Barbados Dollar"},
               {value:"BYR", name:"Belarussian Ruble"},{value:"BEC", name:"Belgian Franc (convertible)"},{value:"BEF", name:"Belgian Franc (currency union with LUF)"},
               {value:"BEL", name:"Belgian Franc (financial)"},{value:"BZD", name:"Belize Dollar"},{value:"XOF", name:"CFA Franc BCEAO"},
               {value:"BMD", name:"Bermudian Dollar"},{value:"INR", name:"Indian Rupee"},{value:"BTN", name:"Ngultrum"},{value:"BOP", name:"Bolivian peso"},
               {value:"BOB", name:"Boliviano"},{value:"BOV", name:"Mvdol"},{value:"BAM", name:"Convertible Marks"},{value:"BWP", name:"Pula"},{value:"NOK", name:"Norwegian Krone"},
               {value:"BRC", name:"Brazilian cruzado"},{value:"BRB", name:"Brazilian cruzeiro"},{value:"BRL", name:"Brazilian Real"},{value:"BND", name:"Brunei Dollar"},
               {value:"BGN", name:"Bulgarian Lev"},{value:"BGJ", name:"Bulgarian lev A/52"},{value:"BGK", name:"Bulgarian lev A/62"},{value:"BGL", name:"Bulgarian lev A/99"},
               {value:"BIF", name:"Burundi Franc"},{value:"KHR", name:"Riel"},{value:"XAF", name:"CFA Franc BEAC"},{value:"CAD", name:"Canadian Dollar"},{value:"CVE", name:"Cape Verde Escudo"},
               {value:"KYD", name:"Cayman Islands Dollar"},{value:"CLP", name:"Chilean Peso"},{value:"CLF", name:"Unidades de fomento"},{value:"CNX", name:"Chinese People's Bank dollar"},
               {value:"CNY", name:"Yuan Renminbi"},{value:"COP", name:"Colombian Peso"},{value:"COU", name:"Unidad de Valor real"},{value:"KMF", name:"Comoro Franc"},
               {value:"CDF", name:"Franc Congolais"},{value:"NZD", name:"New Zealand Dollar"},{value:"CRC", name:"Costa Rican Colon"},{value:"HRK", name:"Croatian Kuna"},
               {value:"CUP", name:"Cuban Peso"},{value:"CYP", name:"Cyprus Pound"},{value:"CZK", name:"Czech Koruna"},{value:"CSK", name:"Czechoslovak koruna"},
               {value:"CSJ", name:"Czechoslovak koruna A/53"},{value:"DKK", name:"Danish Krone"},{value:"DJF", name:"Djibouti Franc"},
               {value:"DOP", name:"Dominican Peso"},{value:"ECS", name:"Ecuador sucre"},{value:"EGP", name:"Egyptian Pound"},{value:"SVC", name:"Salvadoran colón"},
               {value:"EQE", name:"Equatorial Guinean ekwele"},{value:"ERN", name:"Nakfa"},{value:"EEK", name:"Kroon"},{value:"ETB", name:"Ethiopian Birr"},{value:"FKP", name:"Falkland Island Pound"},
               {value:"FJD", name:"Fiji Dollar"},{value:"FIM", name:"Finnish Markka"},{value:"FRF", name:"French Franc"},{value:"XFO", name:"Gold-Franc"},{value:"XPF", name:"CFP Franc"},
               {value:"DEM", name:"Deutsche Mark"},{value:"GHS", name:"Ghana Cedi"},{value:"GHC", name:"Ghanaian cedi"},{value:"GIP", name:"Gibraltar Pound"},
               {value:"GMD", name:"Dalasi"},{value:"GEL", name:"Lari"},{value:"DDM", name:"East German Mark of the GDR (East Germany)"},
               {value:"GRD", name:"Greek Drachma"},{value:"GTQ", name:"Quetzal"},{"GNF":"Guinea Franc"},{value:"GNE", name:"Guinean syli"},
               {value:"GWP", name:"Guinea-Bissau Peso"},{value:"GYD", name:"Guyana Dollar"},{value:"HTG", name:"Gourde"},{value:"HNL", name:"Lempira"},
               {value:"HKD", name:"Hong Kong Dollar"},{value:"HUF", name:"Forint"},{value:"ISK", name:"Iceland Krona"},{value:"ISJ", name:"Icelandic old krona"},
               {value:"IDR", name:"Rupiah"},{value:"IRR", name:"Iranian Rial"},{value:"IQD", name:"Iraqi Dinar"},{value:"IEP", name:"Irish Pound (Punt in Irish language)"},
               {value:"ILP", name:"Israeli lira"},{value:"ILR", name:"Israeli old sheqel"},{value:"ILS", name:"New Israeli Sheqel"},{value:"ITL", name:"Italian Lira"},
               {value:"JMD", name:"Jamaican Dollar"},{value:"JPY", name:"Yen"},{value:"JOD", name:"Jordanian Dinar"},{value:"KZT", name:"Tenge"},{value:"KES", name:"Kenyan Shilling"},
               {value:"KPW", name:"North Korean Won"},{value:"KRW", name:"Won"},{value:"KWD", name:"Kuwaiti Dinar"},{value:"KGS", name:"Som"},{value:"LAK", name:"Kip"},
               {value:"LAJ", name:"Lao kip"},{value:"LVL", name:"Latvian Lats"},{value:"LBP", name:"Lebanese Pound"},{value:"LSL", name:"Loti"},
               {value:"ZAR", name:"Rand"},{value:"LRD", name:"Liberian Dollar"},{value:"LYD", name:"Libyan Dinar"},{value:"CHF", name:"Swiss Franc"},
               {value:"LTL", name:"Lithuanian Litas"},{value:"LUF", name:"Luxembourg Franc (currency union with BEF)"},{value:"MOP", name:"Pataca"},
               {value:"MKD", name:"Denar"},{value:"MKN", name:"Former Yugoslav Republic of Macedonia denar A/93"},{value:"MGA", name:"Malagasy Ariary"},
               {value:"MGF", name:"Malagasy franc"},{value:"MWK", name:"Kwacha"},{value:"MYR", name:"Malaysian Ringgit"},{value:"MVQ", name:"Maldive rupee"},
               {value:"MVR", name:"Rufiyaa"},{value:"MAF", name:"Mali franc"},{value:"MTL", name:"Maltese Lira"},{value:"MRO", name:"Ouguiya"},
               {value:"MUR", name:"Mauritius Rupee"},{value:"MXN", name:"Mexican Peso"},{value:"MXP", name:"Mexican peso"},{value:"MXV", name:"Mexican Unidad de Inversion (UDI)"},
               {value:"MDL", name:"Moldovan Leu"},{value:"MCF", name:"Monegasque franc (currency union with FRF)"},{value:"MNT", name:"Tugrik"},{value:"MAD", name:"Moroccan Dirham"},
               {value:"MZN", name:"Metical"},{value:"MZM", name:"Mozambican metical"},{value:"MMK", name:"Kyat"},{value:"NAD", name:"Namibia Dollar"},{value:"NPR", name:"Nepalese Rupee"},
               {value:"NLG", name:"Netherlands Guilder"},{value:"ANG", name:"Netherlands Antillian Guilder"},{value:"NIO", name:"Cordoba Oro"},{value:"NGN", name:"Naira"},
               {value:"OMR", name:"Rial Omani"},{value:"PKR", name:"Pakistan Rupee"},{value:"PAB", name:"Balboa"},{value:"PGK", name:"Kina"},{value:"PYG", name:"Guarani"},
               {value:"YDD", name:"South Yemeni dinar"},{value:"PEN", name:"Nuevo Sol"},{value:"PEI", name:"Peruvian inti"},{value:"PEH", name:"Peruvian sol"},
               {value:"PHP", name:"Philippine Peso"},{value:"PLZ", name:"Polish zloty A/94"},{value:"PLN", name:"Zloty"},{value:"PTE", name:"Portuguese Escudo"},
               {value:"TPE", name:"Portuguese Timorese escudo"},{value:"QAR", name:"Qatari Rial"},{value:"RON", name:"New Leu"},{value:"ROL", name:"Romanian leu A/05"},
               {value:"ROK", name:"Romanian leu A/52"},{value:"RUB", name:"Russian Ruble"},{value:"RWF", name:"Rwanda Franc"},{value:"SHP", name:"Saint Helena Pound"},
               {value:"WST", name:"Tala"},{"STD":"Dobra"},{value:"SAR", name:"Saudi Riyal"},{value:"RSD", name:"Serbian Dinar"},{value:"CSD", name:"Serbian Dinar"},
               {value:"SCR", name:"Seychelles Rupee"},{value:"SLL", name:"Leone"},{value:"SGD", name:"Singapore Dollar"},{value:"SKK", name:"Slovak Koruna"},{value:"SIT", name:"Slovenian Tolar"},
               {value:"SBD", name:"Solomon Islands Dollar"},{value:"SOS", name:"Somali Shilling"},{value:"ZAL", name:"South African financial rand (Funds code) (discont"},
               {value:"ESP", name:"Spanish Peseta"},{value:"ESA", name:"Spanish peseta (account A)"},{value:"ESB", name:"Spanish peseta (account B)"},
               {value:"LKR", name:"Sri Lanka Rupee"},{value:"SDD", name:"Sudanese Dinar"},{value:"SDP", name:"Sudanese Pound"},{value:"SDG", name:"Sudanese Pound"},
               {value:"SRD", name:"Surinam Dollar"},{value:"SRG", name:"Suriname guilder"},{value:"SZL", name:"Lilangeni"},{value:"SEK", name:"Swedish Krona"},
               {value:"CHE", name:"WIR Euro"},{value:"CHW", name:"WIR Franc"},{value:"SYP", name:"Syrian Pound"},{value:"TWD", name:"New Taiwan Dollar"},{value:"TJS", name:"Somoni"},
               {value:"TJR", name:"Tajikistan ruble"},{value:"TZS", name:"Tanzanian Shilling"},{value:"THB", name:"Baht"},{value:"TOP", name:"Pa'anga"},
               {value:"TTD", name:"Trinidata and Tobago Dollar"},{value:"TND", name:"Tunisian Dinar"},{value:"TRY", name:"New Turkish Lira"},
               {value:"TRL", name:"Turkish lira A/05"},{value:"TMM", name:"Manat"},{value:"RUR", name:"Russian rubleA/97"},{value:"SUR", name:"Soviet Union ruble"},
               {value:"UGX", name:"Uganda Shilling"},{value:"UGS", name:"Ugandan shilling A/87"},{value:"UAH", name:"Hryvnia"},{value:"UAK", name:"Ukrainian karbovanets"},
               {value:"AED", name:"UAE Dirham"},{value:"GBP", name:"Pound Sterling"},{value:"USN", name:"US Dollar (Next Day)"},{value:"USS", name:"US Dollar (Same Day)"},
               {value:"UYU", name:"Peso Uruguayo"},{value:"UYN", name:"Uruguay old peso"},{value:"UYI", name:"Uruguay Peso en Unidades Indexadas"},
               {value:"UZS", name:"Uzbekistan Sum"},{value:"VUV", name:"Vatu"},{value:"VEF", name:"Bolivar Fuerte"},{value:"VEB", name:"Venezuelan Bolivar"},
               {value:"VND", name:"Dong"},{value:"VNC", name:"Vietnamese old dong"},{value:"YER", name:"Yemeni Rial"},{value:"YUD", name:"Yugoslav Dinar"},
               {value:"YUM", name:"Yugoslav dinar (new)"},{value:"ZRN", name:"Zairean New Zaire"},{value:"ZRZ", name:"Zairean Zaire"},{value:"ZMK", name:"Kwacha"},
               {value:"ZWD", name:"Zimbabwe Dollar"},{value:"ZWC", name:"Zimbabwe Rhodesian dollar"}];


